### ISSUE TITLE
Driver Version Error

### ISSUE THREAD

**Issue by taizoy0725** [yamato1413/WebDriverManager-for-VBA#4]
Function DriverVersionでedgedriver.exe -versionでバージョンを取得していますが、古いものだとバージョンを返さないものがあるようです。その場合ret=""となりエラーとなるため、ファイルがあった場合でも、ret を取得後、""の場合に戻る
If ret = "" Then DriverVersion = "": Exit Function
というコードが必要かと思われます。

**Comment by yamato1413** [comment]
情報提供ありがとうございます。
当該Functionを修正いたしました。
